---
version: '3'
services:
  ksql-server:
    image: confluentinc/cp-ksql-server:5.0.0
    ports:
      - 8088:8088
    depends_on:
      - kafka
    environment:
      KSQL_CUB_KAFKA_TIMEOUT: 300
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_SERVICE_ID: ksql
      KSQL_CONSUMER_ZIPKIN_SENDER_TYPE: "KAFKA"
      KSQL_CONSUMER_ZIPKIN_LOCAL_SERVICE_NAME: "ksql"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "no.sysco.middleware.kafka.interceptor.zipkin.TracingProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "no.sysco.middleware.kafka.interceptor.zipkin.TracingConsumerInterceptor"
    volumes:
      - ./target/kafka-interceptor-zipkin-0.3.3-SNAPSHOT.jar:/usr/share/java/ksql-server/kafka-interceptor-zipkin.jar